apiVersion: v1
kind: Secret
metadata:
  name: giropops-secret
type: Opaque
data: # Inicio dos dados
    username: SmVmZXJzb25fbGluZG8=
    password: Z2lyb3BvcHM=

# kubectl create secret generic giropops-secret --from-literal=username=<SEGREDO> --from-literal=password=giropops
