apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-certificate
  namespace: default
spec:
  dnsNames:
    - "*.sidneiweber.com.br"
  secretName: le-tls
  issuerRef:
    name: le-tls
    kind: ClusterIssuer