apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: whoami-tls
  namespace: whoami
spec:
 acme:
   email: sidnei.weber@gmail.com
   # We use the staging server here for testing to avoid hitting
   server: https://acme-v02.api.letsencrypt.org/directory
   privateKeySecretRef:
     # if not existing, it will register a new account and stores it
     name: whoami-tls
   solvers:
     - http01:
         # The ingressClass used to create the necessary ingress routes
         ingress:
           class: traefik