---
ingressClass:
  enabled: true
  isDefaultClass: true
  fallbackApiVersion: v1
ingressRoute:
  dashboard:
    enabled: false
service:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
globalArguments:
- "--api.insecure=true"
# ports:
#   web:
#     redirectTo: websecure

# helm upgrade --namespace=traefik traefik traefik/traefik --set 'ports.web.redirectTo=websecure'